#!/usr/bin/env bash

set -euo pipefail

readonly PROVIDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../scripts/common.sh
source "$PROVIDER_DIR/../../scripts/common.sh"
# shellcheck source=../../../../providers/workspaces/common.sh
source "$LINUXVM_REPO_DIR/../../providers/workspaces/common.sh"

workspace_require_tools
if [[ "$(uname -s)" != "Darwin" || ! -x "$LINUXVM_UTMCTL" ]]; then
    printf 'The UTM workspace provider is unavailable\n' >&2
    exit 1
fi
if [[ -n "${MACHINE_CONTROL_WORKSPACE_HANDLE:-}" ]]; then
    workspace_refusal capabilities workspace_selection_conflict \
        'Workspace management cannot run through a selected workspace'
    exit $?
fi

current_guarded=false
if [[ "$LINUXVM_WORKSPACE_DEVELOPMENT_PROVEN" == "true" &&
      "$LINUXVM_REQUIRE_MUTATION_GUARD" == "true" &&
      "$LINUXVM_TARGET_ROLE" == "candidate" &&
      "$LINUXVM_UTM_NAME" == "$LINUXVM_WORKSPACE_DEVELOPMENT_NAME" &&
      "$LINUXVM_EXPECTED_NAME" == "$LINUXVM_WORKSPACE_DEVELOPMENT_NAME" &&
      "$LINUXVM_EXPECTED_UUID" == "$LINUXVM_WORKSPACE_DEVELOPMENT_ID" &&
      -n "$LINUXVM_EXPECTED_UUID" ]]; then
    current_guarded=true
fi

UTM_WORKSPACE_CLI="$LINUXVM_UTMCTL"
UTM_WORKSPACE_PROVIDER=utm-macos-linux
UTM_WORKSPACE_STATE_DIR="$LINUXVM_WORKSPACE_STATE_DIR"
UTM_WORKSPACE_CURRENT_GUARDED="$current_guarded"
UTM_WORKSPACE_DEVELOPMENT_NAME="$LINUXVM_WORKSPACE_DEVELOPMENT_NAME"
UTM_WORKSPACE_DEVELOPMENT_ID="$LINUXVM_WORKSPACE_DEVELOPMENT_ID"
UTM_WORKSPACE_DEVELOPMENT_PROVEN="$LINUXVM_WORKSPACE_DEVELOPMENT_PROVEN"
UTM_WORKSPACE_READY_BASE_NAME="$LINUXVM_WORKSPACE_READY_BASE_NAME"
UTM_WORKSPACE_READY_BASE_ID="$LINUXVM_WORKSPACE_READY_BASE_ID"
UTM_WORKSPACE_READY_BASE_PROVEN="$LINUXVM_WORKSPACE_READY_BASE_PROVEN"
UTM_WORKSPACE_ALLOW_SHARED_BASE="$LINUXVM_WORKSPACE_ALLOW_SHARED_BASE"
UTM_WORKSPACE_STORAGE_PATH="$LINUXVM_WORKSPACE_STORAGE_PATH"
UTM_WORKSPACE_MIN_FREE_BYTES="$LINUXVM_WORKSPACE_MIN_FREE_BYTES"
UTM_WORKSPACE_MAX_TEMPORARY="$LINUXVM_WORKSPACE_MAX_TEMPORARY"
UTM_WORKSPACE_MAX_RETAINED="$LINUXVM_WORKSPACE_MAX_RETAINED"
UTM_WORKSPACE_FULL_COPY_FALLBACK="$LINUXVM_WORKSPACE_FULL_COPY_FALLBACK"
UTM_WORKSPACE_ALLOW_FULL_COPY_ONCE="$LINUXVM_WORKSPACE_ALLOW_FULL_COPY_ONCE"
UTM_WORKSPACE_CANDIDATE_PREFIX="$LINUXVM_WORKSPACE_CANDIDATE_PREFIX"
UTM_WORKSPACE_BOOT_TIMEOUT="$LINUXVM_BOOT_TIMEOUT"
UTM_WORKSPACE_SHUTDOWN_TIMEOUT="$LINUXVM_SHUTDOWN_TIMEOUT"

# shellcheck source=../../../../providers/workspaces/utm-macos.sh
source "$LINUXVM_REPO_DIR/../../providers/workspaces/utm-macos.sh"
utm_workspace_main "$@"
