#!/usr/bin/env bash

set -euo pipefail

readonly PROVIDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../scripts/common.sh
source "$PROVIDER_DIR/../../scripts/common.sh"

readonly LIBVIRT_CORE="$WINVM_REPO_DIR/../../providers/libvirt-linux/libvirt_provider.py"

export MC_LIBVIRT_URI="$WINVM_LIBVIRT_URI"
export MC_LIBVIRT_DOMAIN_NAME="$WINVM_LIBVIRT_DOMAIN_NAME"
export MC_LIBVIRT_EXPECTED_UUID="$WINVM_EXPECTED_UTM_ID"
export MC_LIBVIRT_NETWORK="$WINVM_LIBVIRT_NETWORK"
export MC_LIBVIRT_POOL="$WINVM_LIBVIRT_POOL"
export MC_LIBVIRT_VIRSH="$WINVM_LIBVIRT_VIRSH"
export MC_LIBVIRT_QEMU="$WINVM_LIBVIRT_QEMU"
export MC_LIBVIRT_BOOT_TIMEOUT="$WINVM_BOOT_TIMEOUT"
export MC_LIBVIRT_SHUTDOWN_TIMEOUT="$WINVM_SHUTDOWN_TIMEOUT"
export MC_LIBVIRT_EXEC_TIMEOUT="$WINVM_POST_UPDATE_REPORT_TIMEOUT"
export MC_LIBVIRT_MIN_FREE_BYTES="$WINVM_LIBVIRT_MIN_FREE_BYTES"
export MC_LIBVIRT_REQUIRE_SECURE_BOOT=true
export MC_LIBVIRT_REQUIRE_TPM2=true

usage() {
    cat <<'EOF'
Usage: provider.sh COMMAND [ARG...]

Internal libvirt/QEMU/KVM-on-Linux provider. Use bin/winvm instead.
EOF
}

core() {
    "$LIBVIRT_CORE" "$@"
}

source_mutation_authorized() {
    [[ "$WINVM_ALLOW_SOURCE_MUTATION" == 1 ]]
}

persistent_seal_boot_authorized() {
    [[ "$WINVM_ALLOW_PERSISTENT_SEAL_BOOT" == 1 ]]
}

role_allows_operation() {
    local role="$1" operation="$2"
    case "$operation" in
        inspect|status|capabilities|target-id|screenshot|down|shutdown|suspend)
            return 0
            ;;
        seal|export-image)
            [[ "$role" == source || "$role" == candidate || "$role" == seal ]]
            ;;
        disposable-up|delete)
            [[ "$role" == candidate || "$role" == seal ]]
            ;;
        up)
            [[ "$role" == candidate ]] ||
                { [[ "$role" == source ]] && source_mutation_authorized; } ||
                { [[ "$role" == seal ]] && persistent_seal_boot_authorized; }
            ;;
        connect)
            [[ "$role" == candidate || "$role" == seal ]] ||
                { [[ "$role" == source ]] && source_mutation_authorized; }
            ;;
        stage-bootstrap|deploy-ui|product-install|post-update-repair|appliance-certify|generalize|input|force-stop|factory-detach-installer|factory-detach-media)
            [[ "$role" == candidate ]] ||
                { [[ "$role" == source ]] && source_mutation_authorized; }
            ;;
        *) return 1 ;;
    esac
}

target_id() {
    core resolve-uuid
}

pin_target() {
    local role="${1:-}" selected_name="${2:-$WINVM_LIBVIRT_DOMAIN_NAME}"
    if [[ ( $# -lt 1 || $# -gt 2 ) ||
          "$role" != source && "$role" != candidate && "$role" != seal ]]; then
        printf 'Usage: winvm pin-target source|candidate|seal [DOMAIN_NAME]\n' >&2
        return 2
    fi
    local actual_id previous_id="" stable_reads=0 temporary
    export MC_LIBVIRT_DOMAIN_NAME="$selected_name"
    export MC_LIBVIRT_EXPECTED_UUID=""
    while (( stable_reads < 3 )); do
        actual_id="$(core resolve-uuid)" || return
        if [[ "$actual_id" == "$previous_id" ]]; then
            stable_reads=$((stable_reads + 1))
        else
            previous_id="$actual_id"
            stable_reads=1
        fi
        if (( stable_reads < 3 )); then sleep 1; fi
    done
    temporary="$(mktemp "$WINVM_TARGET_FILE.XXXXXX")"
    chmod 600 "$temporary"
    {
        printf '# Generated by winvm pin-target; ignored by Git.\n'
        printf 'WINVM_UTM_NAME=%q\n' "$selected_name"
        printf 'WINVM_LIBVIRT_DOMAIN_NAME=%q\n' "$selected_name"
        printf 'WINVM_EXPECTED_UTM_ID=%q\n' "$actual_id"
        printf 'WINVM_TARGET_ROLE=%q\n' "$role"
    } >"$temporary"
    mv "$temporary" "$WINVM_TARGET_FILE"
    printf 'target pinned: role=%s\n' "$role"
}

assert_target() {
    local operation="${1:-}" output_format="${2:-human}"
    if [[ -z "$operation" ||
          "$output_format" != human && "$output_format" != --json ]]; then
        printf 'Usage: winvm assert-target OPERATION [--json]\n' >&2
        return 2
    fi
    case "$WINVM_TARGET_ROLE" in
        source|candidate|seal) ;;
        *)
            printf 'Target role is unclassified; repair private inventory.\n' >&2
            return 1
            ;;
    esac
    if [[ -z "$WINVM_EXPECTED_UTM_ID" ]]; then
        printf 'Target identity is unpinned; repair private inventory.\n' >&2
        return 1
    fi
    if ! role_allows_operation "$WINVM_TARGET_ROLE" "$operation"; then
        printf 'Target role does not authorize this operation.\n' >&2
        return 1
    fi
    if ! core inspect >/dev/null; then
        printf 'The provider could not resolve the configured target identity.\n' >&2
        return 1
    fi
    if [[ "$output_format" == --json ]]; then
        jq -n --arg provider "$WINVM_PROVIDER" --arg role "$WINVM_TARGET_ROLE" \
            --arg operation "$operation" --arg state "$(core status)" \
            --arg ssh_alias "$WINVM_SSH_HOST" \
            '{schema_version:1,provider:$provider,identity_pin:"verified",
              role:$role,operation:$operation,authorized:true,state:$state,
              transport:{ssh_alias:$ssh_alias}}'
    else
        printf 'target verified: role=%s operation=%s\n' \
            "$WINVM_TARGET_ROLE" "$operation"
    fi
}

provider_capabilities() {
    local output_format="${1:-human}" state
    if [[ "$output_format" != human && "$output_format" != --json ]]; then
        printf 'Usage: winvm capabilities [--json]\n' >&2
        return 2
    fi
    state="$(core status 2>/dev/null || printf unknown)"
    if [[ "$output_format" == --json ]]; then
        jq -n --arg state "$state" \
            '{schema_version:1,provider:"libvirt-linux",state:$state,
              acceleration:{required:"kvm",architecture:"x86_64"},
              lifecycle:{
                suspend:{availability:"unavailable",source:"provider",
                  reasons:["libvirt-suspend-not-adopted"]},
                default_down_action:"guest-shutdown",
                seal:{availability:"unavailable"},
                disposable_start:{availability:"unavailable"},
                export_image:{availability:"unavailable"},
                generalize:{availability:"available",route:"guest_sysprep"}},
              image_factory:{availability:"conditional",
                requires:["x86_64-kvm","q35-uefi","secure-boot","tpm2"]}}'
    else
        printf 'hardware acceleration: kvm (required)\n'
        printf 'architecture: x86_64 (required)\n'
        printf 'suspend: unavailable\n'
        printf 'default down action: guest-shutdown\n'
    fi
}

ensure_running() {
    assert_target up >/dev/null
    core start
}

guest_ipv4() {
    ensure_running
    core ip
}

guest_ipv4_once() {
    assert_target inspect >/dev/null
    core ip
}

ssh_exec() {
    assert_target connect >/dev/null
    local state ip
    state="$(core status)"
    if [[ "$state" != started ]]; then
        if [[ "$WINVM_SSH_ALLOW_START" != true ]]; then
            printf 'The target is not running and start is prohibited.\n' >&2
            return 1
        fi
        ensure_running
    fi
    ip="$(core ip)"
    "$WINVM_SSH_BIN" \
        -o BatchMode=yes -o ProxyCommand=none -o "HostName=$ip" \
        -o "HostKeyAlias=$WINVM_SSH_HOST" -o CheckHostIP=no \
        -p "$WINVM_SSH_PORT" "$WINVM_SSH_HOST" "$@"
}

stage_bootstrap() {
    local public_key="${1:-$HOME/.ssh/id_ed25519.pub}"
    local bootstrap="$WINVM_REPO_DIR/guests/windows/bootstrap-openssh.ps1"
    [[ -r "$public_key" ]] || {
        printf 'Public key is unavailable.\n' >&2
        return 1
    }
    ensure_running
    core push "$bootstrap" 'C:\Users\Public\winvm-bootstrap-openssh.ps1'
    core push "$public_key" 'C:\Users\Public\winvm-host.pub'
    cat <<'EOF'
Bootstrap files staged through the QEMU guest agent. In the Windows guest,
open PowerShell as Administrator and run the staged bootstrap script.
EOF
}

post_update_guest_agent() {
    local profile="${1:-}" nonce="${2:-}"
    if [[ ( "$profile" != Development && "$profile" != Runtime ) ||
          ! "$nonce" =~ ^[A-Za-z0-9-]{8,64}$ ]]; then
        printf 'Usage: provider.sh post-update-guest-agent Development|Runtime NONCE\n' >&2
        return 2
    fi
    local guest_script="C:\Users\Public\winvm-post-update-$nonce.ps1"
    local guest_report="C:\ProgramData\MachineControl\reports\post-update-$nonce.json"
    local pulled_report
    pulled_report="$(mktemp "${TMPDIR:-/tmp}/winvm-post-update.XXXXXX")"
    trap 'rm -f -- "$pulled_report"' RETURN
    ensure_running
    core push "$WINVM_REPO_DIR/guests/windows/post-update.ps1" "$guest_script"
    core exec -- powershell.exe -NoLogo -NoProfile -NonInteractive \
        -ExecutionPolicy Bypass -File "$guest_script" -Mode Repair \
        -Profile "$profile" -Nonce "$nonce" -ReportPath "$guest_report" \
        >/dev/null 2>&1 || true
    core pull "$guest_report" "$pulled_report" || {
        printf 'Guest-agent repair produced no fresh attested report.\n' >&2
        return 1
    }
    jq -e --arg nonce "$nonce" \
        '.schema == "machine-control-windows-post-update/v0" and
         .mode == "repair" and .nonce == $nonce' \
        "$pulled_report" >/dev/null || {
        printf 'Guest-agent repair report was invalid.\n' >&2
        return 1
    }
    cat "$pulled_report"
}

require_outer_ui_allowed() {
    if [[ "$WINVM_FORBID_OUTER_UI" == true ]]; then
        printf 'Refusing host-side libvirt screenshot/input: outer UI is forbidden\n' >&2
        return 1
    fi
}

unsupported() {
    printf 'This libvirt provider operation is not implemented yet\n' >&2
    return 1
}

command="${1:-}"
if [[ -n "$command" ]]; then shift; fi

case "$command" in
    host-doctor) core host-doctor ;;
    status) core status ;;
    capabilities) provider_capabilities "$@" ;;
    target-id) target_id ;;
    pin-target) pin_target "$@" ;;
    assert-target) assert_target "$@" ;;
    up) guest_ipv4 ;;
    ip) guest_ipv4_once ;;
    ssh-exec) ssh_exec "$@" ;;
    stage-bootstrap) assert_target stage-bootstrap >/dev/null; stage_bootstrap "$@" ;;
    post-update-guest-agent)
        assert_target post-update-repair >/dev/null
        post_update_guest_agent "$@"
        ;;
    down|shutdown) assert_target shutdown >/dev/null; core shutdown ;;
    force-stop) assert_target force-stop >/dev/null; core force-stop ;;
    screenshot|type|click|key|scan)
        require_outer_ui_allowed
        unsupported
        ;;
    repair-registration|suspend|seal|disposable-up|export-image|factory-create|factory-detach-installer|factory-detach-media|delete)
        unsupported
        ;;
    *) usage >&2; exit 2 ;;
esac
