#!/usr/bin/env bash

set -euo pipefail

readonly PROVIDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../scripts/common.sh
source "$PROVIDER_DIR/../../scripts/common.sh"
# shellcheck source=../../../../providers/workspaces/common.sh
source "$WINVM_REPO_DIR/../../providers/workspaces/common.sh"

workspace_require_tools
if [[ "$(uname -s)" != Linux ]]; then
    printf 'The libvirt workspace provider requires Linux\n' >&2
    exit 1
fi
if [[ -n "${MACHINE_CONTROL_WORKSPACE_HANDLE:-}" ]]; then
    workspace_refusal capabilities workspace_selection_conflict \
        'Workspace management cannot run through a selected workspace'
    exit $?
fi

export MC_LIBVIRT_URI="$WINVM_LIBVIRT_URI"
export MC_LIBVIRT_DOMAIN_NAME="$WINVM_LIBVIRT_DOMAIN_NAME"
export MC_LIBVIRT_EXPECTED_UUID="$WINVM_EXPECTED_UTM_ID"
export MC_LIBVIRT_NETWORK="$WINVM_LIBVIRT_NETWORK"
export MC_LIBVIRT_POOL="$WINVM_LIBVIRT_POOL"
export MC_LIBVIRT_VIRSH="$WINVM_LIBVIRT_VIRSH"
export MC_LIBVIRT_QEMU="$WINVM_LIBVIRT_QEMU"
export MC_LIBVIRT_BOOT_TIMEOUT="$WINVM_BOOT_TIMEOUT"
export MC_LIBVIRT_SHUTDOWN_TIMEOUT="$WINVM_SHUTDOWN_TIMEOUT"
export MC_LIBVIRT_EXEC_TIMEOUT="$WINVM_POST_UPDATE_REPORT_TIMEOUT"
export MC_LIBVIRT_MIN_FREE_BYTES="$WINVM_LIBVIRT_MIN_FREE_BYTES"
export MC_LIBVIRT_REQUIRE_SECURE_BOOT=true
export MC_LIBVIRT_REQUIRE_TPM2=true

current_guarded=false
if [[ "$WINVM_WORKSPACE_DEVELOPMENT_PROVEN" == true &&
      "$WINVM_TARGET_ROLE" == candidate &&
      "$WINVM_LIBVIRT_DOMAIN_NAME" == "$WINVM_WORKSPACE_DEVELOPMENT_NAME" &&
      "$WINVM_EXPECTED_UTM_ID" == "$WINVM_WORKSPACE_DEVELOPMENT_ID" &&
      -n "$WINVM_EXPECTED_UTM_ID" ]]; then
    current_guarded=true
fi

LIBVIRT_WORKSPACE_CORE="$WINVM_REPO_DIR/../../providers/libvirt-linux/libvirt_provider.py"
LIBVIRT_WORKSPACE_DOMAIN="$WINVM_REPO_DIR/../../providers/libvirt-linux/workspace_domain.py"
LIBVIRT_WORKSPACE_PLATFORM_BIN="$WINVM_REPO_DIR/bin/winvm"
LIBVIRT_WORKSPACE_PROVIDER=libvirt-linux-windows
LIBVIRT_WORKSPACE_STATE_DIR="$WINVM_WORKSPACE_STATE_DIR"
LIBVIRT_WORKSPACE_CLAIM_STATE_DIR="$WINVM_CLAIM_STATE_DIR"
LIBVIRT_WORKSPACE_CURRENT_GUARDED="$current_guarded"
LIBVIRT_WORKSPACE_DEVELOPMENT_NAME="$WINVM_WORKSPACE_DEVELOPMENT_NAME"
LIBVIRT_WORKSPACE_DEVELOPMENT_ID="$WINVM_WORKSPACE_DEVELOPMENT_ID"
LIBVIRT_WORKSPACE_DEVELOPMENT_PROVEN="$WINVM_WORKSPACE_DEVELOPMENT_PROVEN"
LIBVIRT_WORKSPACE_READY_BASE_NAME="$WINVM_WORKSPACE_READY_BASE_NAME"
LIBVIRT_WORKSPACE_READY_BASE_ID="$WINVM_WORKSPACE_READY_BASE_ID"
LIBVIRT_WORKSPACE_READY_BASE_PROVEN="$WINVM_WORKSPACE_READY_BASE_PROVEN"
LIBVIRT_WORKSPACE_ALLOW_SHARED_BASE="$WINVM_WORKSPACE_ALLOW_SHARED_BASE"
LIBVIRT_WORKSPACE_STORAGE_PATH="$WINVM_WORKSPACE_STORAGE_PATH"
LIBVIRT_WORKSPACE_MIN_FREE_BYTES="$WINVM_WORKSPACE_MIN_FREE_BYTES"
LIBVIRT_WORKSPACE_MAX_TEMPORARY="$WINVM_WORKSPACE_MAX_TEMPORARY"
LIBVIRT_WORKSPACE_MAX_RETAINED="$WINVM_WORKSPACE_MAX_RETAINED"
LIBVIRT_WORKSPACE_CANDIDATE_PREFIX="$WINVM_WORKSPACE_CANDIDATE_PREFIX"
LIBVIRT_WORKSPACE_NVRAM_DIRECTORY="$WINVM_LIBVIRT_NVRAM_DIRECTORY"
LIBVIRT_WORKSPACE_NVRAM_TEMPLATE="$WINVM_LIBVIRT_NVRAM_TEMPLATE"

# shellcheck source=../../../../providers/workspaces/libvirt-linux.sh
source "$WINVM_REPO_DIR/../../providers/workspaces/libvirt-linux.sh"
libvirt_workspace_main "$@"
