#!/usr/bin/env bash

set -euo pipefail

readonly PROVIDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../scripts/common.sh
source "$PROVIDER_DIR/../../scripts/common.sh"

usage() {
    cat <<'EOF'
Usage: provider.sh COMMAND [ARG...]

Internal UTM-on-macOS provider. Use bin/winvm instead.
EOF
}

require_utmctl() {
    if [[ "$(uname -s)" != "Darwin" ]]; then
        printf 'The utm-macos provider requires macOS\n' >&2
        exit 1
    fi
    if [[ ! -x "$WINVM_UTMCTL" ]]; then
        printf 'UTM CLI not found at %s\n' "$WINVM_UTMCTL" >&2
        exit 1
    fi
}

require_outer_ui_allowed() {
    if [[ "$WINVM_FORBID_OUTER_UI" == true ]]; then
        printf 'Refusing host-side UTM screenshot/input: outer UI is forbidden\n' >&2
        return 1
    fi
}

vm_status() {
    "$WINVM_UTMCTL" status "$(utm_target_identifier)" 2>/dev/null
}

utm_target_identifier() {
    printf '%s\n' "${WINVM_EXPECTED_UTM_ID:-$WINVM_UTM_NAME}"
}

target_id() {
    local target_name="${1:-$WINVM_UTM_NAME}"
    local expected_id=""
    if [[ $# -eq 0 ]]; then expected_id="$WINVM_EXPECTED_UTM_ID"; fi
    "$WINVM_OSASCRIPT" - "$target_name" "$expected_id" <<'APPLESCRIPT'
on run argv
    set vmName to item 1 of argv
    set expectedId to item 2 of argv
    tell application "UTM"
        if expectedId is not "" then
            set targetVM to first virtual machine whose id is expectedId
        else
            set targetVM to first virtual machine whose name is vmName
        end if
        return id of targetVM
    end tell
end run
APPLESCRIPT
}

pin_target() {
    local role="${1:-}"
    local selected_name="${2:-$WINVM_UTM_NAME}"
    if [[ "$selected_name" == "--configured" ]]; then
        selected_name="$WINVM_CONFIGURED_UTM_NAME"
    fi
    if [[ ( $# -lt 1 || $# -gt 2 ) ||
        "$role" != "source" && "$role" != "candidate" && "$role" != "seal" ]]; then
        printf 'Usage: winvm pin-target source|candidate|seal [VM_NAME|--configured]\n' >&2
        return 2
    fi
    local actual_id="" previous_id="" temporary stable_reads=0
    local deadline=$((SECONDS + 10))
    while (( SECONDS < deadline && stable_reads < 3 )); do
        actual_id="$(target_id "$selected_name")"
        if [[ -n "$actual_id" && "$actual_id" == "$previous_id" ]]; then
            stable_reads=$((stable_reads + 1))
        else
            previous_id="$actual_id"
            stable_reads=1
        fi
        if (( stable_reads < 3 )); then sleep 1; fi
    done
    if [[ -z "$actual_id" || stable_reads -lt 3 ]]; then
        printf 'The provider could not resolve a stable target identity.\n' >&2
        return 1
    fi
    temporary="$(mktemp "$WINVM_TARGET_FILE.XXXXXX")"
    chmod 600 "$temporary"
    {
        printf '# Generated by winvm pin-target; ignored by Git.\n'
        printf 'WINVM_UTM_NAME=%q\n' "$selected_name"
        printf 'WINVM_EXPECTED_UTM_ID=%q\n' "$actual_id"
        printf 'WINVM_TARGET_ROLE=%q\n' "$role"
    } > "$temporary"
    mv "$temporary" "$WINVM_TARGET_FILE"
    printf 'target pinned: role=%s\n' "$role"
}

source_mutation_authorized() {
    [[ "$WINVM_ALLOW_SOURCE_MUTATION" == "1" ]]
}

persistent_seal_boot_authorized() {
    [[ "$WINVM_ALLOW_PERSISTENT_SEAL_BOOT" == "1" ]]
}

role_allows_operation() {
    local role="$1" operation="$2"
    case "$operation" in
        inspect|status|capabilities|target-id|screenshot|down|shutdown|suspend)
            return 0
            ;;
        seal)
            [[ "$role" == "source" || "$role" == "candidate" || "$role" == "seal" ]]
            ;;
        disposable-up|delete|export-image)
            [[ "$role" == "candidate" || "$role" == "seal" ]]
            ;;
        up)
            [[ "$role" == "candidate" ]] ||
                { [[ "$role" == "source" ]] && source_mutation_authorized; } ||
                { [[ "$role" == "seal" ]] && persistent_seal_boot_authorized; }
            ;;
        connect)
            [[ "$role" == "candidate" || "$role" == "seal" ]] ||
                { [[ "$role" == "source" ]] && source_mutation_authorized; }
            ;;
        stage-bootstrap|deploy-ui|product-install|post-update-repair|generalize|input|force-stop|factory-detach-installer|factory-detach-media)
            [[ "$role" == "candidate" ]] ||
                { [[ "$role" == "source" ]] && source_mutation_authorized; }
            ;;
        *)
            return 1
            ;;
    esac
}

assert_target() {
    local operation="${1:-}" output_format="${2:-human}"
    if [[ -z "$operation" || ( "$output_format" != "human" && "$output_format" != "--json" ) ]]; then
        printf 'Usage: winvm assert-target OPERATION [--json]\n' >&2
        return 2
    fi
    case "$WINVM_TARGET_ROLE" in
        source|candidate|seal) ;;
        *)
            printf 'Target role is unclassified; set WINVM_TARGET_ROLE to source, candidate, or seal.\n' >&2
            return 1
            ;;
    esac
    if [[ -z "$WINVM_EXPECTED_UTM_ID" ]]; then
        printf 'Target identity is unpinned; set WINVM_EXPECTED_UTM_ID in ignored configuration.\n' >&2
        return 1
    fi
    local actual_id
    actual_id="$(target_id 2>/dev/null || true)"
    if [[ -z "$actual_id" ]]; then
        printf 'The provider could not resolve the configured target identity.\n' >&2
        return 1
    fi
    local normalized_actual normalized_expected
    normalized_actual="$(printf '%s' "$actual_id" | tr '[:upper:]' '[:lower:]')"
    normalized_expected="$(printf '%s' "$WINVM_EXPECTED_UTM_ID" | tr '[:upper:]' '[:lower:]')"
    if [[ "$normalized_actual" != "$normalized_expected" ]]; then
        printf 'Configured target identity does not match the provider target.\n' >&2
        return 1
    fi
    if ! role_allows_operation "$WINVM_TARGET_ROLE" "$operation"; then
        printf 'Target role %s does not authorize operation %s.\n' \
            "$WINVM_TARGET_ROLE" "$operation" >&2
        return 1
    fi
    if [[ "$output_format" == "--json" ]]; then
        winvm_require_command jq || return
        jq -n \
            --arg provider "$WINVM_PROVIDER" \
            --arg role "$WINVM_TARGET_ROLE" \
            --arg operation "$operation" \
            --arg state "$(vm_status || printf unknown)" \
            --arg ssh_alias "$WINVM_SSH_HOST" \
            '{schema_version: 1, provider: $provider, identity_pin: "verified", role: $role, operation: $operation, authorized: true, state: $state, transport: {ssh_alias: $ssh_alias}}'
    else
        printf 'target verified: role=%s operation=%s\n' \
            "$WINVM_TARGET_ROLE" "$operation"
    fi
}

factory_create() {
    if [[ $# -ne 4 || -z "$1" || -z "$2" || -z "$3" || -z "$4" ]]; then
        printf 'Usage: winvm factory-create NAME WINDOWS_ISO SEED_ISO BOOT_IMAGE\n' >&2
        return 2
    fi
    local destination="$1" windows_iso="$2" seed_iso="$3" boot_image="$4" status
    for media in "$windows_iso" "$seed_iso" "$boot_image"; do
        if [[ ! -f "$media" || ! -r "$media" ]]; then
            printf 'Factory media is absent or unreadable.\n' >&2
            return 1
        fi
    done
    windows_iso="$(cd "$(dirname "$windows_iso")" && pwd -P)/$(basename "$windows_iso")"
    seed_iso="$(cd "$(dirname "$seed_iso")" && pwd -P)/$(basename "$seed_iso")"
    boot_image="$(cd "$(dirname "$boot_image")" && pwd -P)/$(basename "$boot_image")"
    if vm_is_registered "$destination"; then
        printf 'Factory destination is already registered.\n' >&2
        return 1
    fi
    "$WINVM_OSASCRIPT" - "$destination" "$windows_iso" "$seed_iso" \
        "$boot_image" \
        >/dev/null <<'APPLESCRIPT'
on run argv
    set vmName to item 1 of argv
    set windowsIso to POSIX file (item 2 of argv)
    set seedIso to POSIX file (item 3 of argv)
    set bootImage to POSIX file (item 4 of argv)
    tell application "UTM"
        make new virtual machine with properties {backend:qemu, configuration:{name:vmName, architecture:"aarch64", memory:8192, cpu cores:4, hypervisor:true, uefi:true, drives:{{removable:true, source:windowsIso}, {removable:true, source:seedIso}, {removable:true, interface:USB, source:bootImage}, {interface:NVMe, guest size:131072}}, displays:{{hardware:"virtio-ramfb-gl", dynamic resolution:true}}, network interfaces:{{mode:shared}}}}
    end tell
end run
APPLESCRIPT
    status="$("$WINVM_UTMCTL" status "$destination" 2>/dev/null || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'UTM did not create a stopped factory target.\n' >&2
        return 1
    fi
    printf 'factory target created\n'
}

factory_detach_media() {
    local status result removed remaining
    status="$(vm_status || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'Factory media detachment requires a stopped target.\n' >&2
        return 1
    fi
    result="$("$WINVM_OSASCRIPT" - "$WINVM_EXPECTED_UTM_ID" <<'APPLESCRIPT'
on run argv
    set expectedId to item 1 of argv
    tell application "UTM"
        set targetVM to first virtual machine whose id is expectedId
        set vmConfig to configuration of targetVM
        set retainedDrives to {}
        set removedCount to 0
        repeat with driveConfig in drives of vmConfig
            if removable of driveConfig then
                set removedCount to removedCount + 1
            else
                set end of retainedDrives to contents of driveConfig
            end if
        end repeat
        if removedCount > 0 then
            set drives of vmConfig to retainedDrives
            update configuration targetVM with vmConfig
        end if
        set updatedConfig to configuration of targetVM
        set remainingCount to 0
        repeat with driveConfig in drives of updatedConfig
            if removable of driveConfig then
                set remainingCount to remainingCount + 1
            end if
        end repeat
        return (removedCount as text) & tab & (remainingCount as text)
    end tell
end run
APPLESCRIPT
)"
    IFS=$'\t' read -r removed remaining <<< "$result"
    if [[ ! "$removed" =~ ^[0-9]+$ || "$remaining" != "0" ]]; then
        printf 'UTM did not confirm complete removable-media detachment.\n' >&2
        return 1
    fi
    printf 'factory media detached: removed=%s remaining=0\n' "$removed"
}

factory_detach_installer() {
    local status result initial removed remaining
    status="$(vm_status || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'Factory installer detachment requires a stopped target.\n' >&2
        return 1
    fi
    result="$("$WINVM_OSASCRIPT" - "$WINVM_EXPECTED_UTM_ID" <<'APPLESCRIPT'
on run argv
    set expectedId to item 1 of argv
    tell application "UTM"
        set targetVM to first virtual machine whose id is expectedId
        set vmConfig to configuration of targetVM
        set initialCount to 0
        repeat with driveConfig in drives of vmConfig
            if removable of driveConfig then
                set initialCount to initialCount + 1
            end if
        end repeat
        set retainedDrives to {}
        set removedCount to 0
        if initialCount is 3 then
            repeat with driveConfig in drives of vmConfig
                if (removable of driveConfig) and removedCount is 0 then
                    set removedCount to 1
                else
                    set end of retainedDrives to contents of driveConfig
                end if
            end repeat
            set drives of vmConfig to retainedDrives
            update configuration targetVM with vmConfig
        end if
        set updatedConfig to configuration of targetVM
        set remainingCount to 0
        repeat with driveConfig in drives of updatedConfig
            if removable of driveConfig then
                set remainingCount to remainingCount + 1
            end if
        end repeat
        return (initialCount as text) & tab & (removedCount as text) & tab & (remainingCount as text)
    end tell
end run
APPLESCRIPT
)"
    IFS=$'\t' read -r initial removed remaining <<< "$result"
    if [[ "$initial" != "3" || "$removed" != "1" || "$remaining" != "2" ]]; then
        printf 'UTM did not confirm exact installer-only detachment.\n' >&2
        return 1
    fi
    printf 'factory installer detached: removed=1 seed_media_remaining=2\n'
}

vm_export_image() {
    if [[ $# -ne 1 || -z "$1" ]]; then
        printf 'Usage: winvm export-image OUTPUT.utm\n' >&2
        return 2
    fi
    local output="$1" status parent
    if [[ "$output" != /* || "${output##*.}" != "utm" ]]; then
        printf 'Export output must be an absolute .utm path.\n' >&2
        return 2
    fi
    if [[ -e "$output" ]]; then
        printf 'Export output already exists.\n' >&2
        return 1
    fi
    parent="$(dirname "$output")"
    if [[ ! -d "$parent" || ! -w "$parent" ]]; then
        printf 'Export parent is absent or not writable.\n' >&2
        return 1
    fi
    status="$(vm_status || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'Export requires a stopped target.\n' >&2
        return 1
    fi
    "$WINVM_OSASCRIPT" - "$WINVM_EXPECTED_UTM_ID" "$output" <<'APPLESCRIPT'
on run argv
    set expectedId to item 1 of argv
    set outputFile to POSIX file (item 2 of argv)
    tell application "UTM"
        set targetVM to first virtual machine whose id is expectedId
        export targetVM to outputFile
    end tell
end run
APPLESCRIPT
    if [[ ! -d "$output" ]]; then
        printf 'UTM did not produce the requested export bundle.\n' >&2
        return 1
    fi
    "$WINVM_REPO_DIR/scripts/image-manifest.sh" "$output" >/dev/null
    printf 'image exported\n'
}

utm_configuration_devices() {
    local target_identifier selector_kind
    target_identifier="$(utm_target_identifier)"
    selector_kind="$(if [[ -n "$WINVM_EXPECTED_UTM_ID" ]]; then printf id; else printf name; fi)"
    "$WINVM_OSASCRIPT" - "$target_identifier" "$selector_kind" <<'APPLESCRIPT'
on run argv
    set targetIdentifier to item 1 of argv
    set selectorKind to item 2 of argv
    tell application "UTM"
        if selectorKind is "id" then
            set targetVM to first virtual machine whose id is targetIdentifier
        else
            set targetVM to first virtual machine whose name is targetIdentifier
        end if
        set vmConfig to configuration of targetVM
        set outputLines to {}
        repeat with displayConfig in displays of vmConfig
            set end of outputLines to "display\t" & (hardware of displayConfig as text)
        end repeat
        repeat with driveConfig in drives of vmConfig
            set end of outputLines to "drive\t" & (interface of driveConfig as text)
        end repeat
    end tell
    set AppleScript's text item delimiters to linefeed
    return outputLines as text
end run
APPLESCRIPT
}

detect_suspend_capability() {
    SUSPEND_AVAILABILITY="unknown"
    SUSPEND_SOURCE="policy"
    SUSPEND_REASONS=()

    case "$WINVM_SUSPEND_POLICY" in
        enabled)
            SUSPEND_AVAILABILITY="available"
            SUSPEND_SOURCE="configured"
            return
            ;;
        disabled)
            SUSPEND_AVAILABILITY="unavailable"
            SUSPEND_SOURCE="configured"
            SUSPEND_REASONS+=("configured-disabled")
            return
            ;;
        auto) ;;
        *)
            printf 'Invalid WINVM_SUSPEND_POLICY: %s (expected auto, enabled, or disabled)\n' \
                "$WINVM_SUSPEND_POLICY" >&2
            return 2
            ;;
    esac

    SUSPEND_SOURCE="utm-configuration"
    local devices kind hardware normalized
    if ! devices="$(utm_configuration_devices 2>/dev/null)"; then
        SUSPEND_REASONS+=("utm-configuration-unavailable")
        return
    fi

    local found_gpu=0 found_nvme=0
    while IFS=$'\t' read -r kind hardware; do
        normalized="$(printf '%s' "$hardware" | tr '[:upper:]' '[:lower:]')"
        if [[ "$kind" == "display" && "$normalized" == *-gl* && "$found_gpu" -eq 0 ]]; then
            SUSPEND_REASONS+=("utm-qemu-gpu-display")
            found_gpu=1
        elif [[ "$kind" == "drive" && "$normalized" == "nvme" && "$found_nvme" -eq 0 ]]; then
            SUSPEND_REASONS+=("utm-qemu-nvme-disk")
            found_nvme=1
        fi
    done <<< "$devices"

    if (( ${#SUSPEND_REASONS[@]} > 0 )); then
        SUSPEND_AVAILABILITY="unavailable"
    else
        # UTM documents common blockers but does not expose a definitive
        # per-VM capability. Absence of a known blocker is not proof.
        SUSPEND_REASONS+=("utm-support-not-declared")
    fi
}

default_down_action() {
    if [[ "$SUSPEND_AVAILABILITY" == "available" ]]; then
        printf 'suspend\n'
    else
        printf 'guest-shutdown\n'
    fi
}

provider_capabilities() {
    local output_format="human"
    case "${1:-}" in
        "") ;;
        --json) output_format="json" ;;
        *)
            printf 'Usage: winvm capabilities [--json]\n' >&2
            return 2
            ;;
    esac

    detect_suspend_capability || return
    local action state reasons_json='[]'
    action="$(default_down_action)"
    state="$(vm_status || printf 'unknown\n')"

    if [[ "$output_format" == "json" ]]; then
        winvm_require_command jq || return
        if (( ${#SUSPEND_REASONS[@]} > 0 )); then
            reasons_json="$(printf '%s\n' "${SUSPEND_REASONS[@]}" | jq -R . | jq -s .)"
        fi
        jq -n \
            --arg state "$state" \
            --arg availability "$SUSPEND_AVAILABILITY" \
            --arg source "$SUSPEND_SOURCE" \
            --argjson reasons "$reasons_json" \
            --arg action "$action" \
            '{schema_version: 1, state: $state, lifecycle: {suspend: {availability: $availability, source: $source, reasons: $reasons}, default_down_action: $action, seal: {availability: "available", kind: "full_clone", requires: ["source_stopped", "destination_unregistered"]}, disposable_start: {availability: "available", persistence: "discard_on_stop"}, export_image: {availability: "available", kind: "utm_bundle", requires: ["identity_pin", "candidate_or_seal_role", "target_stopped", "new_absolute_output"]}, generalize: {availability: "available", route: "guest_sysprep", requires: ["identity_pin", "candidate_role", "administrator", "no_pending_reboot"]}, delete: {availability: "available", requires: ["configured_target_stopped", "exact_name_confirmation"]}}, image_factory: {availability: "conditional", architecture: "aarch64", requires: ["local_windows_iso", "private_answer_media", "installer_detachment_before_bootstrap", "stopped_media_detachment"]}}'
        return
    fi

    printf 'suspend: %s\n' "$SUSPEND_AVAILABILITY"
    local reason
    for reason in "${SUSPEND_REASONS[@]}"; do
        printf 'suspend-reason: %s\n' "$reason"
    done
    printf 'default-down-action: %s\n' "$action"
    printf 'seal: available (stopped full clone)\n'
    printf 'disposable-start: available (discard on stop)\n'
    printf 'export-image: available (stopped UTM bundle)\n'
    printf 'generalize: available (candidate guest Sysprep)\n'
    printf 'image-factory: conditional (explicit local media)\n'
    printf 'delete: available (stopped exact-name confirmation)\n'
}

vm_is_registered() {
    "$WINVM_UTMCTL" status "$1" >/dev/null 2>&1
}

vm_seal() {
    if [[ $# -ne 1 || -z "$1" ]]; then
        printf 'Usage: winvm seal DESTINATION_NAME\n' >&2
        return 2
    fi
    local destination="$1" status
    if [[ "$destination" == "$WINVM_UTM_NAME" ]]; then
        printf 'Seal destination must differ from the configured source VM.\n' >&2
        return 2
    fi
    status="$(vm_status || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'Seal requires a stopped source VM (current state: %s).\n' \
            "${status:-unknown}" >&2
        return 1
    fi
    if vm_is_registered "$destination"; then
        printf 'Seal destination is already registered.\n' >&2
        return 1
    fi
    "$WINVM_UTMCTL" clone --hide "$(utm_target_identifier)" --name "$destination" \
        >/dev/null
    status="$("$WINVM_UTMCTL" status "$destination" 2>/dev/null || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'UTM did not produce a stopped seal (state: %s).\n' \
            "${status:-unknown}" >&2
        return 1
    fi
    printf 'sealed\n'
}

vm_disposable_up() {
    local status
    status="$(vm_status || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'Disposable start requires a stopped VM (current state: %s).\n' \
            "${status:-unknown}" >&2
        return 1
    fi
    "$WINVM_UTMCTL" start --hide "$(utm_target_identifier)" --disposable >/dev/null
    if ! wait_for_vm_state started "$WINVM_BOOT_TIMEOUT"; then
        printf 'Timed out waiting for disposable VM start (last state: %s).\n' \
            "${LAST_VM_STATUS:-unknown}" >&2
        return 1
    fi
    guest_ipv4
}

vm_delete() {
    if [[ $# -ne 2 || "$1" != "--confirm" || -z "$2" ]]; then
        printf 'Usage: winvm delete --confirm CONFIGURED_VM_NAME\n' >&2
        return 2
    fi
    local confirmation="$2" status
    if [[ "$confirmation" != "$WINVM_UTM_NAME" ]]; then
        printf 'Delete confirmation does not match the configured VM.\n' >&2
        return 2
    fi
    status="$(vm_status || true)"
    if [[ "$status" != "stopped" ]]; then
        printf 'Delete requires the configured VM to be stopped (state: %s).\n' \
            "${status:-unknown}" >&2
        return 1
    fi
    "$WINVM_UTMCTL" delete "$WINVM_EXPECTED_UTM_ID" >/dev/null
    if vm_is_registered "$WINVM_EXPECTED_UTM_ID"; then
        printf 'UTM still reports the deleted VM as registered.\n' >&2
        return 1
    fi
    printf 'deleted\n'
}

print_suspend_unavailable() {
    local joined=""
    if (( ${#SUSPEND_REASONS[@]} > 0 )); then
        joined="$(IFS=,; printf '%s' "${SUSPEND_REASONS[*]}")"
    fi
    printf 'Suspend is %s for this VM%s; use: winvm down\n' \
        "$SUSPEND_AVAILABILITY" "${joined:+ ($joined)}" >&2
}

vm_suspend() {
    detect_suspend_capability || return
    if [[ "$SUSPEND_AVAILABILITY" != "available" ]]; then
        print_suspend_unavailable
        return 1
    fi
    "$WINVM_UTMCTL" suspend --save-state "$(utm_target_identifier)"
}

wait_for_vm_state() {
    local expected="$1" timeout="$2"
    local deadline=$((SECONDS + timeout)) status="unknown"
    while (( SECONDS < deadline )); do
        status="$(vm_status || true)"
        if [[ "$status" == "$expected" ]]; then
            return 0
        fi
        sleep 1
    done
    LAST_VM_STATUS="$status"
    return 1
}

vm_shutdown() {
    local status ip=""
    status="$(vm_status || true)"
    if [[ "$status" == "stopped" ]]; then
        printf 'stopped\n'
        return
    fi
    if [[ "$status" != "started" ]]; then
        ensure_running
    fi

    # Prefer a shutdown initiated by Windows. An SSH disconnect is expected as
    # the guest exits, so provider state is the authoritative result.
    # Probe the guest agent once before SSH. The stable alias normally uses a
    # guest-agent ProxyCommand whose full boot timeout is appropriate for `up`
    # but not for shutdown fallback. When an address is already available,
    # bypass only that proxy while preserving the alias user and host-key name.
    ip="$(guest_ipv4_once || true)"
    if [[ -n "$ip" ]]; then
        "$WINVM_SSH_BIN" \
            -o BatchMode=yes \
            -o ConnectTimeout=10 \
            -o ProxyCommand=none \
            -o HostName="$ip" \
            "$WINVM_SSH_HOST" \
            'shutdown.exe /s /t 0' >/dev/null 2>&1 || true
    fi

    if wait_for_vm_state stopped "$WINVM_GUEST_SHUTDOWN_GRACE"; then
        printf 'stopped\n'
        return
    fi

    # Requesting power-down is the non-destructive provider fallback. Never
    # promote a routine shutdown to force-stop.
    "$WINVM_UTMCTL" stop --request "$(utm_target_identifier)" >/dev/null
    if wait_for_vm_state stopped "$WINVM_SHUTDOWN_TIMEOUT"; then
        printf 'stopped\n'
        return
    fi

    printf 'Timed out waiting for UTM VM %s to shut down (last status: %s)\n' \
        "$WINVM_UTM_NAME" "${LAST_VM_STATUS:-unknown}" >&2
    return 1
}

vm_down() {
    if [[ "$(vm_status || true)" == "stopped" ]]; then
        printf 'stopped\n'
        return
    fi
    detect_suspend_capability || return
    if [[ "$SUSPEND_AVAILABILITY" == "available" ]]; then
        vm_suspend
    else
        vm_shutdown
    fi
}

ensure_running() {
    local status
    status="$(vm_status || true)"
    if [[ "$status" != "started" ]]; then
        "$WINVM_UTMCTL" start --hide "$(utm_target_identifier)" >/dev/null 2>&1 || true
    fi

    local deadline=$((SECONDS + WINVM_BOOT_TIMEOUT))
    while (( SECONDS < deadline )); do
        status="$(vm_status || true)"
        if [[ "$status" == "started" ]]; then
            return 0
        fi
        sleep 1
    done

    printf 'Timed out waiting for UTM VM %s to start (last status: %s)\n' \
        "$WINVM_UTM_NAME" "$status" >&2
    return 1
}

guest_ipv4() {
    ensure_running

    local deadline=$((SECONDS + WINVM_BOOT_TIMEOUT))
    local ip
    while (( SECONDS < deadline )); do
        ip="$(guest_ipv4_once || true)"
        if [[ -n "$ip" ]]; then
            printf '%s\n' "$ip"
            return 0
        fi
        sleep 1
    done

    printf 'Timed out waiting for %s to report an IPv4 address\n' \
        "$WINVM_UTM_NAME" >&2
    return 1
}

guest_ipv4_once() {
    local addresses
    addresses="$("$WINVM_UTMCTL" ip-address \
        "$(utm_target_identifier)" 2>/dev/null || true)"
    printf '%s\n' "$addresses" |
        awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ { print; exit }'
}

input_text() {
    if [[ $# -ne 1 ]]; then
        printf 'Usage: winvm type TEXT\n' >&2
        return 2
    fi
    /usr/bin/osascript - "$WINVM_EXPECTED_UTM_ID" "$1" <<'APPLESCRIPT'
on run argv
    set expectedId to item 1 of argv
    set inputText to item 2 of argv
    tell application "UTM"
        set targetVM to first virtual machine whose id is expectedId
        input keystroke targetVM text inputText
    end tell
end run
APPLESCRIPT
}

input_click() {
    if [[ $# -lt 2 || $# -gt 3 || ! "$1" =~ ^[0-9]+$ || ! "$2" =~ ^[0-9]+$ ]]; then
        printf 'Usage: winvm click X Y [left|right|middle]\n' >&2
        return 2
    fi
    local button="${3:-left}"
    if [[ "$button" != "left" && "$button" != "right" && "$button" != "middle" ]]; then
        printf 'Unknown mouse button: %s\n' "$button" >&2
        return 2
    fi
    /usr/bin/osascript - "$WINVM_EXPECTED_UTM_ID" "$1" "$2" "$button" <<'APPLESCRIPT'
on run argv
    set expectedId to item 1 of argv
    set clickPosition to {(item 2 of argv) as integer, (item 3 of argv) as integer}
    set buttonName to item 4 of argv
    if buttonName is "right" then
        set buttonKind to «constant MsBtMsRt»
    else if buttonName is "middle" then
        set buttonKind to «constant MsBtMsMd»
    else
        set buttonKind to «constant MsBtMsLf»
    end if
    tell application "UTM"
        set targetVM to first virtual machine whose id is expectedId
        input mouse click targetVM at clickPosition with mouse button buttonKind
    end tell
end run
APPLESCRIPT
}

input_scan_codes() {
    if [[ $# -lt 1 ]]; then
        printf 'Usage: winvm scan CODE...\n' >&2
        return 2
    fi
    local code
    for code in "$@"; do
        if [[ ! "$code" =~ ^[0-9]+$ || "$code" -gt 255 ]]; then
            printf 'Scan codes must be decimal bytes (0-255): %s\n' "$code" >&2
            return 2
        fi
    done
    /usr/bin/osascript - "$WINVM_EXPECTED_UTM_ID" "$@" <<'APPLESCRIPT'
on run argv
    set expectedId to item 1 of argv
    set scanCodes to {}
    repeat with rawCode in items 2 thru -1 of argv
        set end of scanCodes to rawCode as integer
    end repeat
    tell application "UTM"
        set targetVM to first virtual machine whose id is expectedId
        input scan code targetVM codes scanCodes
    end tell
end run
APPLESCRIPT
}

input_key() {
    if [[ $# -ne 1 ]]; then
        printf 'Usage: winvm key NAME\n' >&2
        return 2
    fi
    case "$1" in
        enter)             input_scan_codes 28 156 ;;
        escape)            input_scan_codes 1 129 ;;
        tab)               input_scan_codes 15 143 ;;
        win-r)             input_scan_codes 224 91 19 147 224 219 ;;
        win-d)             input_scan_codes 224 91 32 160 224 219 ;;
        ctrl-shift-escape) input_scan_codes 29 42 1 129 170 157 ;;
        alt-f4)            input_scan_codes 56 62 190 184 ;;
        ctrl-alt-delete)   input_scan_codes 29 56 224 83 224 211 184 157 ;;
        *)
            printf 'Unknown key name: %s\n' "$1" >&2
            return 2
            ;;
    esac
}

stage_bootstrap() {
    if [[ "$WINVM_GUEST_DRIVER" != "windows" ]]; then
        printf 'SSH bootstrap is not implemented for guest driver: %s\n' \
            "$WINVM_GUEST_DRIVER" >&2
        return 1
    fi

    local public_key="${1:-$HOME/.ssh/id_ed25519.pub}"
    local bootstrap="$WINVM_REPO_DIR/guests/windows/bootstrap-openssh.ps1"
    if [[ ! -r "$public_key" ]]; then
        printf 'Public key not found: %s\n' "$public_key" >&2
        return 1
    fi

    ensure_running
    "$WINVM_UTMCTL" file push "$(utm_target_identifier)" \
        'C:\Users\Public\winvm-bootstrap-openssh.ps1' < "$bootstrap"
    "$WINVM_UTMCTL" file push "$(utm_target_identifier)" \
        'C:\Users\Public\winvm-host.pub' < "$public_key"

    cat <<'EOF'
Bootstrap files staged. In the Windows VM, open PowerShell as Administrator
and run:

powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass `
  -File C:\Users\Public\winvm-bootstrap-openssh.ps1

Then configure the SSH alias and run: bin/winvm doctor
EOF
}

post_update_guest_agent() {
    local profile="${1:-}" nonce="${2:-}"
    if [[ ( "$profile" != "Development" && "$profile" != "Runtime" ) ||
        ! "$nonce" =~ ^[A-Za-z0-9-]{8,64}$ ]]; then
        printf 'Usage: provider.sh post-update-guest-agent Development|Runtime NONCE\n' >&2
        return 2
    fi
    winvm_require_command jq || return
    ensure_running

    local guest_script="C:\\Users\\Public\\winvm-post-update-$nonce.ps1"
    local guest_report="C:\\ProgramData\\MachineControl\\reports\\post-update-$nonce.json"
    local pulled_report
    pulled_report="$(mktemp "${TMPDIR:-/tmp}/winvm-post-update.XXXXXX")"

    "$WINVM_UTMCTL" file push "$(utm_target_identifier)" \
        "$guest_script" < \
        "$WINVM_REPO_DIR/guests/windows/post-update.ps1"

    # UTM guest execution has returned false success on an earlier appliance.
    # Ignore this delivery result and accept only a fresh nonce-bound report
    # retrieved independently through guest-agent file transfer.
    "$WINVM_UTMCTL" exec "$(utm_target_identifier)" --cmd \
        powershell.exe -NoLogo -NoProfile -NonInteractive \
        -ExecutionPolicy Bypass -File "$guest_script" \
        -Mode Repair -Profile "$profile" -Nonce "$nonce" \
        -ReportPath "$guest_report" >/dev/null 2>&1 || true

    local deadline=$((SECONDS + WINVM_POST_UPDATE_REPORT_TIMEOUT))
    while (( SECONDS < deadline )); do
        if "$WINVM_UTMCTL" file pull "$(utm_target_identifier)" \
                "$guest_report" >"$pulled_report" 2>/dev/null &&
            jq -e --arg nonce "$nonce" \
                '.schema == "machine-control-windows-post-update/v0" and
                 .mode == "repair" and .nonce == $nonce' \
                "$pulled_report" >/dev/null; then
            cat "$pulled_report"
            rm -f -- "$pulled_report"
            return 0
        fi
        sleep 2
    done
    rm -f -- "$pulled_report"
    printf 'Guest-agent repair produced no fresh attested report.\n' >&2
    return 1
}

require_utmctl
command="${1:-}"
if [[ -n "$command" ]]; then shift; fi

case "$command" in
    status) vm_status ;;
    capabilities) provider_capabilities "$@" ;;
    target-id) target_id ;;
    pin-target) pin_target "$@" ;;
    assert-target) assert_target "$@" ;;
    up) assert_target up >/dev/null; guest_ipv4 ;;
    ip) assert_target inspect >/dev/null; guest_ipv4_once ;;
    screenshot) require_outer_ui_allowed; exec "$PROVIDER_DIR/screenshot" "$@" ;;
    type) require_outer_ui_allowed; assert_target input >/dev/null; input_text "$@" ;;
    click) require_outer_ui_allowed; assert_target input >/dev/null; input_click "$@" ;;
    key) require_outer_ui_allowed; assert_target input >/dev/null; input_key "$@" ;;
    scan) require_outer_ui_allowed; assert_target input >/dev/null; input_scan_codes "$@" ;;
    stage-bootstrap) assert_target stage-bootstrap >/dev/null; stage_bootstrap "$@" ;;
    post-update-guest-agent) assert_target post-update-repair >/dev/null; post_update_guest_agent "$@" ;;
    seal) assert_target seal >/dev/null; vm_seal "$@" ;;
    disposable-up) assert_target disposable-up >/dev/null; vm_disposable_up "$@" ;;
    export-image) assert_target export-image >/dev/null; vm_export_image "$@" ;;
    factory-create) factory_create "$@" ;;
    factory-detach-installer) assert_target factory-detach-installer >/dev/null; factory_detach_installer ;;
    factory-detach-media) assert_target factory-detach-media >/dev/null; factory_detach_media ;;
    delete) assert_target delete >/dev/null; vm_delete "$@" ;;
    down) assert_target down >/dev/null; vm_down ;;
    suspend) assert_target suspend >/dev/null; vm_suspend ;;
    shutdown) assert_target shutdown >/dev/null; vm_shutdown ;;
    force-stop) assert_target force-stop >/dev/null; "$WINVM_UTMCTL" stop --force "$(utm_target_identifier)" ;;
    *) usage >&2; exit 2 ;;
esac
