#!/usr/bin/env bash

set -euo pipefail

readonly PROVIDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../scripts/common.sh
source "$PROVIDER_DIR/../../scripts/common.sh"
# shellcheck source=../../../../providers/workspaces/common.sh
source "$LINUXVM_REPO_DIR/../../providers/workspaces/common.sh"

workspace_require_tools
if [[ "$(uname -s)" != Linux ]]; then
    printf 'The libvirt workspace provider requires Linux\n' >&2
    exit 1
fi
if [[ -n "${MACHINE_CONTROL_WORKSPACE_HANDLE:-}" ]]; then
    workspace_refusal capabilities workspace_selection_conflict \
        'Workspace management cannot run through a selected workspace'
    exit $?
fi

export MC_LIBVIRT_URI="$LINUXVM_LIBVIRT_URI"
export MC_LIBVIRT_DOMAIN_NAME="$LINUXVM_LIBVIRT_DOMAIN_NAME"
export MC_LIBVIRT_EXPECTED_UUID="$LINUXVM_EXPECTED_UUID"
export MC_LIBVIRT_NETWORK="$LINUXVM_LIBVIRT_NETWORK"
export MC_LIBVIRT_POOL="$LINUXVM_LIBVIRT_POOL"
export MC_LIBVIRT_VIRSH="$LINUXVM_LIBVIRT_VIRSH"
export MC_LIBVIRT_QEMU="$LINUXVM_LIBVIRT_QEMU"
export MC_LIBVIRT_BOOT_TIMEOUT="$LINUXVM_BOOT_TIMEOUT"
export MC_LIBVIRT_SHUTDOWN_TIMEOUT="$LINUXVM_SHUTDOWN_TIMEOUT"
export MC_LIBVIRT_EXEC_TIMEOUT="$LINUXVM_EXEC_TIMEOUT"
export MC_LIBVIRT_MIN_FREE_BYTES="$LINUXVM_LIBVIRT_MIN_FREE_BYTES"
export MC_LIBVIRT_REQUIRE_SECURE_BOOT=false
export MC_LIBVIRT_REQUIRE_TPM2=false

current_guarded=false
if [[ "$LINUXVM_WORKSPACE_DEVELOPMENT_PROVEN" == true &&
      "$LINUXVM_REQUIRE_MUTATION_GUARD" == true &&
      "$LINUXVM_TARGET_ROLE" == candidate &&
      "$LINUXVM_LIBVIRT_DOMAIN_NAME" == "$LINUXVM_WORKSPACE_DEVELOPMENT_NAME" &&
      "$LINUXVM_EXPECTED_NAME" == "$LINUXVM_WORKSPACE_DEVELOPMENT_NAME" &&
      "$LINUXVM_EXPECTED_UUID" == "$LINUXVM_WORKSPACE_DEVELOPMENT_ID" &&
      -n "$LINUXVM_EXPECTED_UUID" ]]; then
    current_guarded=true
fi

LIBVIRT_WORKSPACE_CORE="$LINUXVM_REPO_DIR/../../providers/libvirt-linux/libvirt_provider.py"
LIBVIRT_WORKSPACE_DOMAIN="$LINUXVM_REPO_DIR/../../providers/libvirt-linux/workspace_domain.py"
LIBVIRT_WORKSPACE_PLATFORM_BIN="$LINUXVM_REPO_DIR/bin/linuxvm"
LIBVIRT_WORKSPACE_PROVIDER=libvirt-linux-linux
LIBVIRT_WORKSPACE_STATE_DIR="$LINUXVM_WORKSPACE_STATE_DIR"
LIBVIRT_WORKSPACE_CLAIM_STATE_DIR="$LINUXVM_CLAIM_STATE_DIR"
LIBVIRT_WORKSPACE_CURRENT_GUARDED="$current_guarded"
LIBVIRT_WORKSPACE_DEVELOPMENT_NAME="$LINUXVM_WORKSPACE_DEVELOPMENT_NAME"
LIBVIRT_WORKSPACE_DEVELOPMENT_ID="$LINUXVM_WORKSPACE_DEVELOPMENT_ID"
LIBVIRT_WORKSPACE_DEVELOPMENT_PROVEN="$LINUXVM_WORKSPACE_DEVELOPMENT_PROVEN"
LIBVIRT_WORKSPACE_READY_BASE_NAME="$LINUXVM_WORKSPACE_READY_BASE_NAME"
LIBVIRT_WORKSPACE_READY_BASE_ID="$LINUXVM_WORKSPACE_READY_BASE_ID"
LIBVIRT_WORKSPACE_READY_BASE_PROVEN="$LINUXVM_WORKSPACE_READY_BASE_PROVEN"
LIBVIRT_WORKSPACE_ALLOW_SHARED_BASE="$LINUXVM_WORKSPACE_ALLOW_SHARED_BASE"
LIBVIRT_WORKSPACE_STORAGE_PATH="$LINUXVM_WORKSPACE_STORAGE_PATH"
LIBVIRT_WORKSPACE_MIN_FREE_BYTES="$LINUXVM_WORKSPACE_MIN_FREE_BYTES"
LIBVIRT_WORKSPACE_MAX_TEMPORARY="$LINUXVM_WORKSPACE_MAX_TEMPORARY"
LIBVIRT_WORKSPACE_MAX_RETAINED="$LINUXVM_WORKSPACE_MAX_RETAINED"
LIBVIRT_WORKSPACE_CANDIDATE_PREFIX="$LINUXVM_WORKSPACE_CANDIDATE_PREFIX"
LIBVIRT_WORKSPACE_NVRAM_DIRECTORY="$LINUXVM_LIBVIRT_NVRAM_DIRECTORY"
LIBVIRT_WORKSPACE_NVRAM_TEMPLATE="$LINUXVM_LIBVIRT_NVRAM_TEMPLATE"

# shellcheck source=../../../../providers/workspaces/libvirt-linux.sh
source "$LINUXVM_REPO_DIR/../../providers/workspaces/libvirt-linux.sh"
libvirt_workspace_main "$@"
